# Generated by Django 2.1.7 on 2019-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapath', '0002_auto_20190318_1208'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='datapath',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='datapath.Datapath'),
            preserve_default=False,
        ),
    ]
