# Generated by Django 2.1.7 on 2019-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_datapath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.IntegerField(choices=[('A+', 'A+'), ('A-', 'A-'), ('R+', 'R+'), ('R-', 'R-'), ('Q1', 'QI'), ('Q2', 'QII'), ('Q3', 'QIII'), ('Q4', 'QIV')], default=0),
            preserve_default=False,
        ),
    ]
