# Generated by Django 2.1.7 on 2019-03-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstDatapath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datapath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_datapath', models.IntegerField()),
                ('const_datapath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.Feeder')),
            ],
        ),
    ]
